project_id = "gjnvxzsforfrxjanxqnq"

[functions.create-admin-user]
verify_jwt = false

[functions.create-client-user]
verify_jwt = false

[functions.provision-existing-clients]
verify_jwt = false

[functions.get-vapid-public-key]
verify_jwt = false

[functions.generate-vapid-keys]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false